### ISSUE TITLE
Should it clear all childNodes in between?

### ISSUE THREAD

**Issue by luwes** [WebReflection/hyperhtml-wire#4]
Just read your proposal here https://github.com/whatwg/dom/issues/736 👍 

This is a good lightweight solution! I'm running into issues with document fragments myself with caching etc. (unrelated to this project)

As I was looking through the code I saw the use of the range to clear the children and maybe some more?

Question: should it clear all nodes in between the first and last child?

Probably unlikely but there could be some extra nodes appended in the mean time that you didn't mean to remove. Maybe it should only look at the stored childNodes?

---

~~Not so familiar with `.valueOf()`. Are there cases when this method is called automatically? Does `parent.append(myWireObject);` work automatically? this would be neat!~~

tested https://codesandbox.io/s/sleepy-cannon-ny0bh

**Comment by WebReflection** [comment]
Check uwire too 😉
https://github.com/WebReflection/uwire
